name: Build ARMv7a

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true
      
    - name: Build ARMv7a
      run: |
        ./gradlew assembleDebug --info --stacktrace
      env:
        ANDROID_ABI: "armeabi-v7a"
        
    - name: Create output directory
      run: mkdir -p v7output

    - name: Copy APK to output directory
      run: |
        cp app/build/outputs/apk/debug/rikkahub_*_armeabi-v7a-debug.apk v7output/
        ls -l v7output

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-armv7a
        path: v7output
        compression-level: 9
