name: Build ARMv7a Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: '发布标签 (例如: v1.0.0)'
        required: true
        type: string
      release_title:
        description: '发布标题'
        required: true
        type: string
      release_notes:
        description: '发布说明'
        required: true
        type: string
      is_prerelease:
        description: '是否为预发布版本'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true
      
    - name: Build ARMv7a
      run: |
        ./gradlew assembleRelease --info --stacktrace
      env:
        ANDROID_ABI: "armeabi-v7a"
        
    - name: Create output directory
      run: mkdir -p v7output

    - name: Copy APK to output directory
      run: |
        cp app/build/outputs/apk/release/rikkahub_*_armeabi-v7a-release.apk v7output/
        ls -l v7output

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-armv7a
        path: v7output
        compression-level: 9

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        name: ${{ github.event.inputs.release_title }}
        body: ${{ github.event.inputs.release_notes }}
        draft: false
        prerelease: ${{ github.event.inputs.is_prerelease }}
        files: v7output/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
